name: pluse_board
version: "1.0.0"
profile: pluse_board

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  pluse_board:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +dataset: fitbit_mart
